version: '3'

services:
  api-gateway:
    image: kong
    container_name: api_gateway
    volumes:
      - ./kong.conf:/etc/kong/kong.conf
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: ${API_GATEWAY_DB_HOST}
      KONG_PG_USER: ${API_GATEWAY_DB_USERNAME}
      KONG_PG_PASSWORD: ${API_GATEWAY_DB_PASSWORD}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:${API_GATEWAY_ADMIN_PORT}, 0.0.0.0:${API_GATEWAY_ADMIN_SSL_PORT} ssl
    ports:
      - ${API_GATEWAY_PROXY_PORT}:${API_GATEWAY_PROXY_PORT}
      - ${API_GATEWAY_PROXY_SSL_PORT}:${API_GATEWAY_PROXY_SSL_PORT}
      - ${API_GATEWAY_ADMIN_PORT}:${API_GATEWAY_ADMIN_PORT}
      - ${API_GATEWAY_ADMIN_SSL_PORT}:${API_GATEWAY_ADMIN_SSL_PORT}
    command: kong start -vv
    depends_on:
      - api-gateway-db
      - api
    links:
      - api
  
  api-gateway-db:
    image: postgres:9.6
    container_name: api_gateway_db
    environment:
      POSTGRES_USER: ${API_GATEWAY_DB_USERNAME}
      POSTGRES_PASSWORD: ${API_GATEWAY_DB_PASSWORD}
      POSTGRES_DB: ${API_GATEWAY_DB_NAME}
    ports:
      - ${API_GATEWAY_DB_PORT}:${API_GATEWAY_DB_PORT}
    volumes:
      - ./api-gateway-db:/var/lib/postgresql/data

  api-gateway-ui:
    image: pocketdigi/kong-admin-ui:0.5.3
    container_name: api_gateway_ui
    ports:
      - ${API_GATEWAY_ADMIN_UI_PORT}:80
    depends_on:
      - api-gateway

  api:
    image: node:16.13
    container_name: api
    working_dir: /home/node/app
    environment:
      NODE_ENV: ${ENVIRONMENT}
    volumes:
      - ./:/home/node/app
    command: npm start
    ports:
      - ${API_PORT}:${API_PORT}

  # cache:
  #   image: redis

  # auth:
  #   image: 
  